Implemented basic player movement
horizon19/cave-flier pull request #1
Opened 2017-05-01 23:05 UTC by CerberusOne

-Implemented basic player movement to fly up, down, right and left. We have to make the movement more "smooth" in the future.
-Implemented very basic cave environment with obstacles. 
-Player can't move through a obstacle (just for testing, change to "death" state in the future)
-Player can still move through cave walls (again, change to "death" in future)
-There is a function called OnCollisionEnter inside the playerMovement script attached to the player object. Update this function for player collision events with obstacles and walls.

Also FYI, if replacing this project in the future, make sure you update the Editor of the new project so you can commit it to a git repo:
-Edit > Project Settings > Editor 
-Change Version Control > Mode to "Visible Meta Files"
-Change Asset Serialization > Mode to "Force Text"

2017-05-01 23:11 UTC, jacobfrank4 requested changes

2017-05-01 23:11 UTC, jacobfrank4 commented on Cave Flier/Assets/Scripts/cameraMovement.cs
> +public class cameraMovement : MonoBehaviour {
brace should be on new line

2017-05-01 23:11 UTC, jacobfrank4 commented on Cave Flier/Assets/Scripts/cameraMovement.cs
> +	void Start () {
brace should on new line

2017-05-01 23:11 UTC, jacobfrank4 commented on Cave Flier/Assets/Scripts/playerMovement.cs
> +public class playerMovement : MonoBehaviour {
brace should be on new line

2017-05-01 23:11 UTC, jacobfrank4 commented on Cave Flier/Assets/Scripts/playerMovement.cs
> +	void Start () {
brace should be on new line

2017-05-02 00:30 UTC, CerberusOne commented on Cave Flier/Assets/Scripts/cameraMovement.cs
> +public class cameraMovement : MonoBehaviour {
file not needed anymore, deleted

2017-05-02 00:34 UTC, jacobfrank4 requested changes

2017-05-02 00:34 UTC, jacobfrank4 commented on Cave Flier/Assets/Scripts/playerMovement.cs
> +	void Start ()
incorrect spacing.  the function call and comment are further indented than the opening brace.

2017-05-02 00:41 UTC, jacobfrank4 approved these changes

2017-05-02 00:41 UTC, jacobfrank4 approved these changes

2017-05-02 00:41 UTC, jacobfrank4 approved these changes

2017-05-02 00:41 UTC, jacobfrank4 approved these changes

2017-05-02 00:41 UTC, merged